const image = document.getElementById("main-image");
const imageDesc = document.getElementById("image-desc");
const listOfImages = [
  {
    link: "https://www.nepaltraveladventure.com/blog/wp-content/uploads/2020/02/ktm-1024x548.jpg",
    desc: "Kathmandu Durbar Square, also known as Basantapur Durbar and Hanuman Dhoka, is an old durbar square in Kathmandu's city center. In the heart of old Kathmandu city, Basantapur never fails to impress first time visitors with its intricate wood carvings and rich history. Hanuman Dhoka was built during the Licchavi period (4th to 8th centuries AD), and King Pratap Malla extended the property significantly in the 17th century.  With the highest concentration of old structures, the square is home to several palaces, courtyards, and temples. It is also known as 'the Museum of Temples' because there are over 50 temples in the square. Handicraft shops may be found in the courtyards around Gaddi Baithak, where you can see a variety of attractive purchasable handicrafts.\nAmong the 50 temples that lie in the vicinity, lies the temple of the titular deity, Taleju Bhawani. The Durbar is divided into two courtyards, the outer Kasthamandap, Kumari Ghar, and Shiva-Parvati Temple, and the inner section consisting of Hanuman Dhoka and the main palace. Some floors have been converted to museums dedicated to three generations of Shah kings of Nepal. Most parts of the palace premises are open to tourists throughout the week.",
  },
  {
    link: "https://cdn4.iguzzini.com/getmedia/941d01fc-9448-43a8-b84c-0a80094ef490/stupa-Nepal-iGuzzini-02?width=1500&height=1000",
    desc: "Boudhanath is one of the main stupas in Nepal and indeed the whole of South Asia and, since 1979, has been a UN World Heritage Site. There are several legends surrounding its origins, but the first historical mention of the Boudha stupa date back to the fifth century AD. In April 2015, a 7.8 magnitude earthquake hit Nepal, destroying the stupa. Following the appeal launched by guru Gong Qiao to rebuild it, the disciples of the Guru Banma Charity Foundation took on the task of providing lighting for the complex. From above, Boudhanath looks like an enormous mandala, the geometric figure containing numerous other geometric figures that is one of the main symbols of Vedic culture. As in all Tibetan mandalas, four Dhyāna-Buddhas (constructions with Buddha eyes) mark the four cardinal points. The fifth Buddha, Vairocana, is placed in the centre, on the dome’s white hemisphere. All the numbers found in this stupa have symbolic significance. Each Buddha is the embodiment of one of the five elements – earth, water, fire, air and either. The nine levels represent the mythical Mount Meru, the centre of the cosmos in Hindu and Buddhist mythology. The thirteen rings from the base to the pinnacle symbolise the path to enlightenment, or “Bodhi”, the term which gives the stupa its name. At the bottom, the two circular plinths supporting the hemisphere of the stupa symbolise water. The goal of the project was to provide uniform lighting so the building would stand out on the landscape without creating light pollution. This was achieved with MaxiWoody spotlights installed on poles on all four sides of the building. The spotlights’ 12° optics fitted with cylindrical anti-glare screens are aimed at different heights so that they illuminate the dome and the square tower topped by a 13-step pyramid symbolising the ‘stairway’ to enlightenment. Lastly, the golden canopy representing air and the spire representing ether are lit at a colour temperature of 3000 K. All present, worshippers and tourists alike, were deeply moved when the new system was switched on for the first time.",
  },
  {
    link: "https://www.holidaystonepal.in/media/files/Blogs/Pashupatinath-Temple-Photos/Pashupatinath-Temple.png",
    desc: "The Pashupatinath Temple, dedicated to Lord Shiva and located on the banks of the holy Bagmati River in Kathmandu, Nepal, is a timeless spiritual and cultural symbol.\nThe architectural masterpiece is designed in the Nepali pagoda style and is embellished with intricate carvings and beautiful decorations that highlight Nepal's rich historical and artistic history. People come from all over the world to visit this holy Hindu shrine and take part in rituals that have been practiced for generations. As one of the four most important religious sites in Asia and believed to be the world's biggest and oldest Shiva temple, Pashupatinath has a strong spiritual impact on many people.Its status as a UNESCO World Heritage Site adds to its cultural and historical value. The site covers a large area of 246 hectares (2.56 KM square) and has 518 smaller shrines, ashrams, and ghats along the holy river. Additionally, it is the largest temple complex in all of Nepal. The temple complex is not only a great example of Nepalese architecture, but it also has other important temples that add to its beauty. The Vasuki Nath Temple, the Bhairav Nath Temple, and the Guhyeshwari Temple all add to the spiritual atmosphere, making it a place where religion, architecture, and custom all come together.\nIt's a unique and peaceful experience to sit or just be near Pashupatinath. A calming ambience is created by the rhythmic chants and rituals, while the air is filled with the aroma of incense. Whether one is a casual observer or a committed pilgrim, the surroundings convey a timeless spirituality that invites contemplation and reflection. There is a sense of tradition and dedication in the air around the temple that goes back hundreds of years. By soaking in the serene atmosphere, Pashupatinath transforms into a spiritual haven that goes beyond the ordinary, providing a unique opportunity for inner peace and connection with the divine. Let us take a closer look at the parts of this spiritually enlightened place.",
  },
  {
    link: "https://www.altitudehimalaya.com/media/files/Blog/WHS/Swayambhu/Swayambhu_banner2.png",
    desc: "Find peace and prayers on the little hillock of Swaymbhunath in the northwest of Kathmandu Valley. Visitors for whom the name was a tongue twister have called it 'Monkey Temple' from the 1970s. Swayambhu, overlooks most parts of the valley giving visitors a panoramic view of the city. The stupa has stood as a hallmark of faith and harmony for centuries with Hindu temples and deities incorporated in this Buddhist site. The glory of Kathmandu Valley is said to have started from this point.\nResting on a hillock 3 km west of Kathmandu, Swayambhu is one of the holiest Buddhist stupas in Nepal. It is said to have evolved spontaneously when the valley was created out of a primordial lake more than 2,000 years ago. This stupa is the oldest of its kind in Nepal and has numerous shrines and monasteries on its premises.\nSwayambhu literally means 'self-existent one'. Believed to date back to 460 A.D., it was built by King Manadeva and by the 13th century, it had become an important center of Buddhism. Legend has it that Swayambhu was born out of a lotus flower that bloomed in the middle of a lake that once spread across the Kathmandu Valley once was. The largest image of the Sakyamuni Buddha in Nepal sits on a high pedestal on the western boundary of Swayambhu beside the Ring Road. Behind the hilltop is a temple dedicated to Manjusri or Saraswati - the Goddess of learning. Chaityas, statues and shrines of Buddhist and Hindu deities fill the stupa complex. The base of the hill is almost entirely surrounded by prayer wheels and deities. Devotees can be seen circumambulating the stupa at all times.\nExceedingly steep stone steps that lead up to the shrine is quite a challenge. However, there is also a motor road going up almost to the top from where it is a short walk. A large number of Buddhists and Hindus alike visit Swayambhu throughout the day. This shrine is perhaps the best place to observe religious harmony in Nepal. The largest crowds of people are seen here on Buddha's birthday which usually falls in May each year.\nSome important monuments to see in this area\n\nThe huge gold plated Vajra ‘thunderbolt’ set in the east side of the stupa.",
  },
];

const randomChoice =
  listOfImages[Math.ceil(Math.random() * listOfImages.length - 1)];

image.src = randomChoice.link;
imageDesc.textContent = randomChoice.desc;
